name: serc_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pytorch
  - pytorch-cuda=12.1  # 사용 중인 CUDA 버전에 맞춰 조정 가능 (11.8 or 12.1)
  - pip:
    - pyyaml
    - nltk
    - tqdm
    - openai
    - anthropic
    - transformers[torch]
    - accelerate
    - bitsandbytes
    - python-dotenv
    - langchain-community
    - tavily-python
    # Project local install
    - -e .